### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by stazrad** [GlobalHack/cemaritan-ui#5]
There's download ability on the history table - this will make a call to the backend and get a link to an S3 download

**Comment by MattPitlyk** [comment]
This is no longer a button.
This is no longer on the History page.
It is on the Downloads page.

- When user clicks on "Download" link for an item on the Downloads table, webpage needs to fetch the secure download link from organization/{org_id}/downloads/{download_id}/link. 
- Display modal with "Download Now" link that links to the secure link returned by previous bullet.
- Modal should include warning that download link will expire in "2 minutes".
- If the link is clicked after it is expired, is there a way to capture that and notify the user? (A nice to have, as long as we have the warning in the previous bullet.)

**Comment by ktmathews89** [comment]
The UI for this is now complete.
